---
###############################################################################
# Assert Settings
###############################################################################
# Sanity check options to stop preventable errors and accidental data deletion.

- name: 'Assert | required configuration files'
  ansible.builtin.assert:
    quiet: true
    that: 'copyparty_srv_config | length > 0'
    fail_msg: |
      ╭───────────────────────────────────────────────────────────────────╮
      │                                                                   │
      │                   Configuration file required.                    │
      │                                                                   │
      ├───────────────────────────────────────────────────────────────────╯
      │ copyparty requires configuration file sourced from ansible
      │ controller.
      │
      │ copyparty_srv_config: {{ copyparty_srv_config }}
