---
###############################################################################
# Configure Services
###############################################################################

- name: '{{ "Config | filesystem | set " ~ copyparty___app._cfg }}'
  ansible.builtin.template:
    src: '{{ copyparty__cfg._file }}'
    dest: '{{ copyparty___app._cfg }}'
    owner: '{{ copyparty__cfg._uid }}'
    group: '{{ copyparty__cfg._gid }}'
    mode: '0640'
