---
###############################################################################
# Services
###############################################################################

- name: '{{ "Services | systemd | create " ~ copyparty___app._service }}'
  ansible.builtin.template:
    src: 'systemd/copyparty.service.j2'
    dest: '{{ copyparty___app._service }}'
    owner: 'root'
    group: 'root'
    mode: '0644'

- name: 'Services | systemd | daemon reload'
  ansible.builtin.systemd:
    daemon_reload: true

- name: 'Services | systemd | enable'
  ansible.builtin.systemd:
    name: 'copyparty.service'
    enabled: true
