---
###############################################################################
# Services
###############################################################################

- name: '{{ "Services | systemd | create " ~ copyparty__cfg._service }}'
  notify: 'Handlers | enable copyparty'
  ansible.builtin.template:
    src: 'systemd/copyparty.service.j2'
    dest: '{{ copyparty__cfg._service }}'
    owner: 'root'
    group: 'root'
    mode: '0644'
