---
- name: 'Converge'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Converge | import role variables'
      ansible.builtin.include_vars:
        file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~ "/vars/main.yml"
          }}'

    - name: 'Converge | role | r_pufky.media.copyparty'
      ansible.builtin.include_role:
        name: 'r_pufky.media.copyparty'

    - name: '{{ "Converge | test | minimal " ~ copyparty___app._cfg }}'
      ansible.builtin.include_role:
        name: 'r_pufky.data.test'
        tasks_from: 'copy.yml'
      vars:
        test_name: '{{ "Converge | test | minimal " ~ copyparty___app._cfg }}'
        test_src: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/copyparty.conf.role_defaults"
          }}'
        test_file: '{{ copyparty___app._cfg }}'
        test_owner: 'copyparty'
        test_group: 'copyparty'
        test_mode: '0640'
        test_diff: true

    # Re-run with user test copyparty.conf.
    - name: 'Converge | role | r_pufky.media.copyparty'
      ansible.builtin.include_role:
        name: 'r_pufky.media.copyparty'
      vars:
        copyparty_cfg_file: '{{
            lookup("env", "MOLECULE_PROJECT_DIRECTORY") ~
            "/molecule/files/copyparty.conf"
          }}'
        copyparty_flg_maintenance: false
        copyparty_flg_install: false
        copyparty_flg_config: true
        copyparty_flg_start: true
